Allow for setting IP or Hostname
dalmatinerdb/dqe_idx_pg pull request #29
Opened 2016-10-29 21:27 UTC by patrobinson

Same change as https://github.com/dalmatinerdb/ddb_connection/pull/2. This allows for the use of hostnames.

2016-10-29 23:01 UTC, Licenser requested changes

2016-10-29 23:01 UTC, Licenser commented on src/dqe_idx_pg.erl
> +        {ok, Host, Port} ->
this is not correct please compare to the left side.

2016-10-30 05:46 UTC, patrobinson commented on src/dqe_idx_pg.erl
> +        {ok, Host, Port} ->
Thanks fixed

2016-10-30 14:00 UTC, Licenser requested changes

2016-10-30 14:00 UTC, Licenser commented on priv/dqe_idx_pg.schema
>   [{default, {"127.0.0.1", 5432}},
Sorry for only catching this now didn't saw it earlier, as long as the backend has a default it **always** will be set to backend_host / backend_port can't ever take effect.

2016-10-31 15:39 UTC, Licenser approved these changes

2016-10-31 15:39 UTC, Licenser commented
Looks good :D thanks mate!

2016-10-31 15:39 UTC, merged