Configurable worker timeout
dalmatinerdb/dqe_idx_pg pull request #37
Opened 2017-04-04 15:41 UTC by davecromberge

Allows clients to override the default gen_server worker timeout for long-running queries.

2017-04-04 17:01 UTC, Licenser requested changes

2017-04-04 17:01 UTC, Licenser commented on priv/dqe_idx_pg.schema
> +  {datatype, integer}]}.
there is a time datatype for cuttlefish, a better approach here would be:
```erlang
[{default, "5s"},
   {datatype, {time, ms}}]}.
```

2017-04-05 10:54 UTC, szarsti commented
It is probably a good idea, to wait for #36 getting merge. I can see that they both will conflict, but it is straight forward one. I can resolve it as soon as that pull request is accepted.

2017-04-05 10:58 UTC, szarsti commented on priv/dqe_idx_pg.schema
> +  {datatype, integer}]}.
Very neat!

2017-04-05 15:49 UTC, Licenser approved these changes

2017-04-05 15:49 UTC, merged